name: quran-hadith
version: 2.0.6
summary: Qur'ān Hadith
description: |
  Qur'ān Hadith is an Online Quran and Hadith application with fashion interface,
  smooth performance and more features to sharpens your focus on what you are reading or listening.

confinement: classic
base: core22
grade: stable # must be 'stable' to release into candidate/stable channels

architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  dbus-quran-hadith:
    interface: dbus
    bus: session
    name: com.kherld.quran_hadith

apps:
  quran-hadith:
    command: quran_hadith
    extensions: [gnome]
    slots:
      - dbus-quran-hadith
    plugs:
      - network
      - audio-playback
      - pulseaudio
      - desktop
      - desktop-legacy
      - home
      - wayland
      - x11
      - unity7
      - opengl
    environment:
      # PulseAudio configuration for just_audio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/pulse/native
      PULSE_RUNTIME_PATH: $XDG_RUNTIME_DIR/pulse

parts:
  quran-hadith:
    source: .
    plugin: flutter
    flutter-channel: stable
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - libblkid-dev
      - liblzma-dev
      - pkg-config
      - libkeybinder-3.0-dev
    stage-packages:
      - libgtk-3-0
      - libglu1-mesa
      - libkeybinder-3.0-0
      # Audio libraries for just_audio (minimal dependencies)
      - libpulse0
      - libasound2
