name: quran-hadith
version: 2.0.2
summary: Qur'ān Hadith
description: |
  Qur'ān Hadith is an Online Quran and Hadith application with fashion interface,
  smooth performance and more features to sharpens your focus on what you are reading or listening.

confinement: strict
base: core22
grade: stable # must be 'stable' to release into candidate/stable channels

architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  dbus-quran-hadith:
    interface: dbus
    bus: session
    name: com.kherld.quran_hadith

apps:
  quran-hadith:
    command: quran_hadith
    extensions: [gnome]
    slots:
      - dbus-quran-hadith
    plugs:
      - network
      - audio-playback
      - pulseaudio
      - desktop
      - desktop-legacy
      - home
      - wayland
      - x11
      - unity7
      - opengl

parts:
  quran-hadith:
    source: .
    plugin: flutter
    flutter-channel: stable
    flutter-target: lib/main.dart
    override-prime: |
      craftctl default
      arch_triplet="${CRAFT_ARCH_TRIPLET:-${SNAPCRAFT_ARCH_TRIPLET}}"
      target_dir="$CRAFT_PRIME/usr/lib/${arch_triplet}"
      if [ -d "$target_dir" ]; then
        mpv_so=$(find "$target_dir" -maxdepth 1 -name 'libmpv.so.*' -print -quit)
        if [ -n "$mpv_so" ] && [ ! -e "$target_dir/libmpv.so" ]; then
          ln -sf "$(basename "$mpv_so")" "$target_dir/libmpv.so"
        fi
      fi
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - libblkid-dev
      - liblzma-dev
      - pkg-config
      - libkeybinder-3.0-dev
    stage-packages:
      - libgtk-3-0
      - libglu1-mesa
      - libkeybinder-3.0-0
      # media_kit runtime dependencies (libmpv)
      - libmpv1
      # GStreamer runtime libraries for just_audio
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      # PulseAudio support
      - libpulse0
      - pulseaudio-utils
